Improved (mainly rewrote) pbuilder-dist. (Other insignificant changes.)

diff --git a/pbuilder-dist b/pbuilder-dist
--- a/pbuilder-dist
+++ b/pbuilder-dist
@@ -1,11 +1,15 @@
 #!/bin/sh
 # Copyright (C) Jamin W. Collins <jcollins@asgardsrealm.net>
-# License: Public Domain
+#                and Jordan Mantha <mantha@ubuntu.com>
+# Copyright 2007 (C) Siegfried-A. Gevatter <siggi.gevatter@gmail.com>
+# License: GPLv2 or later
 #
 # This script is a wrapper to use pbuilder with many different
 # distributions / versions.
 #
-# Name this script 'pbuilder-dapper', 'pbuilder-feisty', 'pbuilder-gutsy', etc.
+# If you want to use this copy of the script only for a single distribution
+# / version, rename it to 'pbuilder-dapper', 'pbuilder-feisty', 'pbuilder-gutsy', 
+# or whatever it is.
 #
 # The only variable you really might need to change is BASE_DIR, if you
 # don't want pbuilder stuff in your home directory.
@@ -14,34 +18,85 @@
 
 BASE_DIR="$HOME/pbuilder"
 
-OPERATION=$1
-DISTRIBUTION=`basename $0 | cut -f2 -d '-'`
-PROCEED=false
+if [ ! -z `echo \`basename $0\` | grep '-'`  ]
+then
+    if [ $# -lt 1 ]
+    then
+        echo "Insufficient number of arguments."
+        echo "Usage: $0 <operation>"
+        exit 1
+    fi
 
-case $OPERATION in
-   create|update|build|clean|login|execute )
-      PROCEED=true
-      ;;
+    DISTRIBUTION=`basename $0 | cut -f2 -d '-'`
+    OPERATION=$1
+    shift 1
+else
+    if [ $# -lt 2 ]
+    then
+        echo "Insufficient number of arguments."
+        echo "Usage: $0 <distribution> <operation>"
+        exit 1
+    fi
+    
+    DISTRIBUTION=$1
+    OPERATION=$2
+    shift 2
+fi
+
+
+case $DISTRIBUTION in
+    #warty|hoary|breezy)
+    dapper|edgy|feisty|gutsy)
+        ARCHIVE="http://archive.ubuntu.com/ubuntu"
+        COMPONENTS="universe multiverse"
+        ;;
+    
+    oldstable|sarge|stable|etch|testing|lenny|unstable|sid|experimental)
+        ARCHIVE="http://ftp.debian.org"
+        COMPONENTS="main contrib non-free"
+        ;;
+    
+    *)
+        echo "Warning: Unknown distribution «$DISTRIBUTION»."
+        echo -n "Continue [y/N]? "
+        read continue
+        
+        if [ "$continue" != 'y' ] && [ "$continue" != 'Y' ]
+        then
+            echo " Aborting..."
+            exit 1
+        fi
+        
+        ARCHIVE="http://archive.ubuntu.com/ubuntu"
+        COMPONENTS="universe multiverse"
+        ;;
 esac
 
-if [[ $PROCEED = true ]]; then
-   shift 
-   if [ ! -d $BASE_DIR/${DISTRIBUTION}_result ]
-   then mkdir -p $BASE_DIR/${DISTRIBUTION}_result/
-   fi
-   sudo pbuilder $OPERATION \
-      --basetgz $BASE_DIR/$DISTRIBUTION-base.tgz \
-      --distribution $DISTRIBUTION \
-      --buildresult $BASE_DIR/$DISTRIBUTION_result \
-      --othermirror "deb http://archive.ubuntu.com/ubuntu $DISTRIBUTION universe multiverse" $@
-else
-   echo "Invalid command..."
-   echo "Valid commands are:"
-   echo "   create"
-   echo "   update"
-   echo "   build"
-   echo "   clean"
-   echo "   login"
-   echo "   execute"
-   exit 1
+
+case $OPERATION in
+    create|update|build|clean|login|execute)
+        ;;
+    
+    *)
+        echo "Unrecognized argument. Please use one of those:"
+        echo "    create"
+        echo "    update"
+        echo "    build"
+        echo "    clean"
+        echo "    login"
+        echo "    execute"
+        exit 1
+        ;;
+esac
+
+
+if [ ! -d $BASE_DIR/${DISTRIBUTION}_result ]
+then
+    mkdir -p $BASE_DIR/${DISTRIBUTION}_result
 fi
+
+sudo pbuilder $OPERATION \
+    --basetgz $BASE_DIR/$DISTRIBUTION-base.tgz \
+    --distribution $DISTRIBUTION \
+    --buildresult $BASE_DIR/$DISTRIBUTION_result \
+    --othermirror "deb $ARCHIVE $DISTRIBUTION $COMPONENTS" $@
